"""first init db

Revision ID: c2eef4331780
Revises: 0e75c15489dd
Create Date: 2017-09-03 15:49:21.806000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2eef4331780'
down_revision = '0e75c15489dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info')
    op.add_column('users', sa.Column('arrange', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('arrangewant', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('exam', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('grade', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('group', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('premission', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tel', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('time', sa.Integer(), nullable=True))
    op.drop_index('username', table_name='users')
    op.create_unique_constraint(None, 'users', ['name'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('username', 'users', ['username'], unique=True)
    op.drop_column('users', 'time')
    op.drop_column('users', 'tel')
    op.drop_column('users', 'premission')
    op.drop_column('users', 'name')
    op.drop_column('users', 'group')
    op.drop_column('users', 'grade')
    op.drop_column('users', 'exam')
    op.drop_column('users', 'arrangewant')
    op.drop_column('users', 'arrange')
    op.create_table('info',
    sa.Column('card_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('tel', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('arrangewant', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('arrange', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('premission', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('group', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('grade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('exam', mysql.TEXT(), nullable=True),
    sa.Column('time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('card_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
